name: tecno_image_view
description: Um app para visualizar imagens de Serviços de cloud
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  dio: ^5.5.0+1
  download: ^1.0.0
  easy_image_viewer: ^1.5.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  html: ^0.15.4
  image_editor_plus: ^1.0.6
  insta_image_viewer: ^1.0.4
  interactiveviewer_gallery: ^0.6.0
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
